# Good multistage build script: https://github.com/vuejs-templates/pwa/issues/152

version: "3"
services:
  client:
    build: .
    ports:
      - 80:80
    volumes:
      - .:/home/hash_rebel/rebelheadquarters
    # TODO: put environment variables here
    #environment:
