<template>
  <div class="footer">
    <ul>
      <li>
        <a
          href="https://github.com/HashRebel/rebel-headquarters-web/tree/master/docs"
          target="_blank"
        >
          Core Docs
        </a>
      </li>
      <li>
        <a
          href="http://brianhenze.com"
          target="_blank"
        >
          Blog
        </a>
      </li>
      <li>
        <a
          href="https://twitter.com/HashRebel"
          target="_blank"
        >
          Twitter
        </a>
      </li>
      <br>
    </ul>
  </div>
</template>
