<template>
  <div class="footer">
    <div class="footer-copyright">
      © 2018 Hash Rebel
    </div>
    <div>
      <img
        src="../assets/images/icons/hash_rebel/main-fist-code-inlay.svg"
        height=100px
        width=100px
      >
    </div>
    <div class="footer-social-media-icons">
      <ul>
        <li>
          <a
            href="https://github.com/HashRebel/rebel-headquarters-web/tree/master/docs"
            target="_blank"
          >
            <img
              src="../assets/images/icons/social-media/github-original.svg"
              alt="Blog"
            >
          </a>
        </li>
        <li>
          <a
            href="https://steemit.com/@hashrebel"
            target="_blank"
          >
            <img
              src="../assets/images/icons/social-media/steemit-original.svg"
              alt="Blog"
            >
          </a>
        </li>
        <li>
          <a
            href="https://t.me/hash_rebel"
            target="_blank"
          >
            <img
              src="../assets/images/icons/social-media/telegram-original.svg"
              alt="Blog"
            >
          </a>
        </li>
        <li>
          <a
            href="https://medium.com/@henze.brian"
            target="_blank"
          >
            <img
              src="../assets/images/icons/social-media/medium-original.svg"
              alt="Blog"
            >
          </a>
        </li>
        <li>
          <a
            href="https://hub.docker.com/u/hashrebel/"
            target="_blank"
          >
            <img
              src="../assets/images/icons/social-media/docker-original.svg"
              alt="Twitter"
            >
          </a>
        </li>
        <li>
          <a
            href="https://twitter.com/HashRebel"
            target="_blank"
          >
            <img
              src="../assets/images/icons/social-media/twitter-original.svg"
              alt="Twitter"
            >
          </a>
        </li>
        <br>
      </ul>
    </div>
  </div>
</template>
